### ISSUE TITLE
Add a new project Drum Kit Online App

### ISSUE THREAD

**Issue by Srishti2128** [khushi-purwar/WebDev-ProjectKart#48] opened 2022-02-28 16:06 UTC
**Project Title**
Drum Kit Online

**Project Description**

Free online drum game where you can play drum beats, solos along to your favorite music, **by clicking on the screen or with your PC keyboard**. The way this website would work that we’ve got a number of keys on the webpage that represents different drums in a typical drum set and when you click on any of those buttons then you’ll get the corresponding sound of the drum. And in addition you can also use the keys on the keyboard to have a sound effect.

![Screenshot 2022-02-28 212214](https://user-images.githubusercontent.com/90510806/156015544-5797e16f-ddad-445a-9df5-0ccb54f6ed2a.png)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**The project is currently live at** - https://srishti2128.github.io/Drum-Kit
**GitHub Repo for the Project** - https://github.com/Srishti2128/Drum-Kit

**Kindly assign me this task** @khushi-purwar so I can start working on it and make a pull request as soon as possible. I am a GSSOC'22 participant as a contributor.

**Comment by Kushal-2002** [comment] 2022-02-28 16:08
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by Anish1411** [comment] 2022-02-28 18:50
I already made same kind of project , plz assign it to me

**Comment by Anish1411** [comment] 2022-03-01 05:51
please merge my pr #68

**Comment by Srishti2128** [comment] 2022-03-01 06:04
The issue needs to be assigned first by the project admin and only after that the PR can be made as said in GSSOC guidelines. Since the issue hasn't been assigned yet, please assign it to me @khushi-purwar

**Comment by khushi-purwar** [comment] 2022-03-01 10:00
@Srishti2128 you can work on it

**Comment by khushi-purwar** [comment] 2022-03-01 10:01
@Kushal-2002 and @Anish1411 you cannot work on this issue, as issue is open by @Srishti2128 so issue will be assigned on the basis of first come first serve. You can raise any other issue

**Comment by khushi-purwar** [comment] 2022-03-01 10:02
@Anish1411 you cannot create PR until the issue is not assigned to you.

**Comment by Srishti2128** [comment] 2022-03-01 10:17
Thanks for the assignment !!

**Comment by Srishti2128** [comment] 2022-03-01 17:16
I have made the Pull Request #111 . Kindly review and merge it.
Thank You !!

**Closed** 2022-03-03 16:37 UTC
Labels: GSSOC22
