### ISSUE TITLE
Add Rock Paper Scissors Game

### ISSUE THREAD

**Issue by rajaditya28** [khushi-purwar/WebDev-ProjectKart#179] opened 2022-03-04 12:30 UTC
**Project title**
Rock Paper Scissors

**Project Description**
This webapp allows a user to play the conventional game of rock paper scissors against the computer and decides on the basis of user's move and computer's move, that who won or whether it was a tie round.

The game is available at : https://rajaditya28.github.io/Rock-Paper-Scissors/

**Screenshot**

![Screenshot 2022-03-04 170358](https://user-images.githubusercontent.com/68824237/156763577-3002f368-d61c-4b91-8610-63e63cb89d3c.png)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

I would like to add this project. Please assign me the issue @khushi-purwar  @meinhoonharsh so I can get on it right away and make a PR as soon as possible.

**Comment by meinhoonharsh** [comment] 2022-03-04 12:49
It's yours now @rajaditya28

**Comment by ronitrangwani** [comment] 2022-03-04 13:56
I would like to work on this issue under GSSOC'22. Can you assign this to me?

**Comment by rajaditya28** [comment] 2022-03-04 15:42
Have made the PR #191 . Please review and merge it.
Thanks !

**Comment by meinhoonharsh** [comment] 2022-03-04 16:29
> I would like to work on this issue under GSSOC'22. Can you assign this to me?

The issue is already assigned to someone, you can create another issue

**Closed** 2022-03-07 02:15 UTC
Labels: GSSOC22, Level3
